Repository oicr-gsi/vidarr, pull requests merged in 2021-06, with the labels that each got.

#96 Expand details for writing plugins
  plugin-guide.md
Labels: documentation

#98 Pass through stderr from calculate script
  vidarr-cli/src/main/java/ca/on/oicr/gsi/vidarr/cli/TestValidatorScript.java
Labels: enhancement

#101 Create directory entries in Cromwell ZIP
  vidarr-cromwell/src/main/java/ca/on/oicr/gsi/vidarr/cromwell/CromwellWorkflowEngine.java
Labels: bug

#100 Allow really large unload queries
  vidarr-server/src/main/java/ca/on/oicr/gsi/vidarr/server/Main.java
Labels: bug

#102 Add index to `analysis_external_id` table
  vidarr-server/src/main/resources/db/migration/V0007__analysisext_idx.sql
Labels: cleanup

#103 Fix provenance query
  vidarr-server/src/main/java/ca/on/oicr/gsi/vidarr/server/Main.java
Labels: bug

#104 Remove version export restriction
  vidarr-server/src/main/java/ca/on/oicr/gsi/vidarr/server/Main.java
Labels: bug

#109 Improve performance of `/api/status` endpoint
  vidarr-server/src/main/java/ca/on/oicr/gsi/vidarr/server/Main.java
  vidarr-server/src/main/resources/db/migration/V0008__active_operation_idx.sql
Labels: cleanup, enhancement

#112 Move dependency-plugin config outside <executions>
  pom.xml
Labels: bug
